name: CI-workflow

on: 
  pull_request:
  push:
    branches:
      - develop

jobs:
  run_tests:
    runs-on: macos-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v1
      - name: Install Shellcheck
        run: brew install shellcheck
      - name: Run tests
        run: ./tests/test_runner
        shell: bash
    

